//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WALK_IN_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kamar()
        {
            this.Tamu = new HashSet<Tamu>();
        }
    
        public int Id { get; set; }
        public string NoKamar { get; set; }
        public string Tipe { get; set; }
        public string Fasilitas { get; set; }
        public string Kapasitas { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public Nullable<bool> Tersedia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tamu> Tamu { get; set; }
    }
}
