//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WALK_IN_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservasi
    {
        public int Id { get; set; }
        public string KodeReservasi { get; set; }
        public string NoIdTamu { get; set; }
        public string UsernameAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Tamu Tamu { get; set; }
    }
}
